package org.nuxeo.android.layout;


public class StaticLayouts {

	public final static String DEFAULT_LAYOUT = "{ " + LayoutJSONParser.WIDGETS_DEF + "= ["
		+ "{name='title', type='text', attributeName='dc:title', label='Title'},"
		+ "{name='description', type='text', attributeName='dc:description', label='Description'},"
		+ "{name='valid', type='date', attributeName='dc:valid', label='Validity'},"
		+ "{name='nature', type='selectOne', attributeName='dc:nature', label='Nature' , "
		+ " selectOptions : "
		+ "[ { itemValue : 'accomodationApplicationForm' , itemLabel : 'Accomodation application form'},"
		+ " { itemValue : 'acknowledgement' , itemLabel : 'Acknowledgement of receipt'},"
		+ " { itemValue : 'application' , itemLabel : 'Application'},"
		+ " { itemValue : 'article' , itemLabel : 'Article'},"
		+ " { itemValue : 'assessment' , itemLabel : 'Assessment'},"
		+ " { itemValue : 'bankAccountDetails' , itemLabel : 'Bank account details'},"
		+ " { itemValue : 'booklet' , itemLabel : 'Booklet'},"
		+ " { itemValue : 'card' , itemLabel : 'Card'},"
		+ " { itemValue : 'CDRom' , itemLabel : 'CD Rom'},"
		+ " { itemValue : 'certificate' , itemLabel : 'Certificate'},"
		+ " { itemValue : 'contract' , itemLabel : 'Contract'},"
		+ " { itemValue : 'convocation' , itemLabel : 'Convocation'},"
		+ " { itemValue : 'credit' , itemLabel : 'Credit'},"
		+ " { itemValue : 'decree' , itemLabel : 'Decree'},"
		+ " { itemValue : 'deliveryNote' , itemLabel : 'Delivery note'},"
		+ " { itemValue : 'email' , itemLabel : 'Email'},"
		+ " { itemValue : 'endorsement' , itemLabel : 'Endorsement'},"
		+ " { itemValue : 'fax' , itemLabel : 'Fax'},"
		+ " { itemValue : 'internshipReport' , itemLabel : 'Internship report'},"
		+ " { itemValue : 'invoice' , itemLabel : 'Invoice'},"
		+ " { itemValue : 'leaveApplication' , itemLabel : 'Leave application'},"
		+ " { itemValue : 'letter' , itemLabel : 'Letter'},"
		+ " { itemValue : 'loanApplication' , itemLabel : 'Loan application'},"
		+ " { itemValue : 'medicalCertificate' , itemLabel : 'Medical certificate'},"
		+ " { itemValue : 'memo' , itemLabel : 'Memo'},"
		+ " { itemValue : 'note' , itemLabel : 'Note'},"
		+ " { itemValue : 'notice' , itemLabel : 'Notice'},"
		+ " { itemValue : 'notification' , itemLabel : 'Notification'},"
		+ " { itemValue : 'order' , itemLabel : 'Order'},"
		+ " { itemValue : 'pressReview' , itemLabel : 'Press review'},"
		+ " { itemValue : 'procedure' , itemLabel : 'Procedure'},"
		+ " { itemValue : 'purchaseOrder' , itemLabel : 'Purchase order'},"
		+ " { itemValue : 'quotation' , itemLabel : 'Quotation'},"
		+ " { itemValue : 'report' , itemLabel : 'Report'},"
		+ " { itemValue : 'serviceCertificate' , itemLabel : 'Service certificate'},"
		+ " { itemValue : 'trainingApplication' , itemLabel : 'Training application'},"
		+ " { itemValue : 'worksheet' , itemLabel : 'Worksheet'} ]"
		+ " }"
		+ "], "
		+ " " + LayoutJSONParser.ROWS_DEF + "= ["
		+ "['title'],"
		+ "['description'],"
		+ "['valid'],"
		+ "['nature']"
		+ "]}";


}
